### ISSUE TITLE
Make Circle CI jobs more robust against network failure

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolasdk#11]
* When Flathub is overloaded, the installation of GNOME SDK fails and the whole job too.
* Repeat the failed download? This would overload Flathub even more...
* Maintain a mirror of GNOME SDK? Possible.
* Create a periodically updated docker image of Fedora 29 + updates + GNOME SDK? This would made jobs much faster. RPM updates took ages...

**Comment by jiri-janousek** [comment]
Example ob job failure because of network error: https://circleci.com/gh/tiliado/nuvola-app-amazon-cloud-player/5

**Comment by a-m-s** [comment]
Here's another: https://circleci.com/gh/tiliado/nuvola-app-jupiter-broadcasting/5

**Comment by jiri-janousek** [comment]
The [tiliado/nuvolasdk-ci](https://hub.docker.com/r/tiliado/nuvolasdk-ci) docker image is now used to run Circle CI for web app scripts. No action from script maintainers is required.

In addition, the build directory is archived when the CI fails, e.g. [tiliado/nuvola-app-jupiter-broadcasting/10](https://circleci.com/gh/tiliado/nuvola-app-jupiter-broadcasting/10#artifacts/containers/0).
