### ISSUE TITLE
https://pypi.org/simple/nuvolsdk/ returns 404 error

### ISSUE THREAD

**Issue by ghost** [tiliado/nuvolasdk#13]
Currently it's impossible to install from PyPI

`Collecting nuvolsdk
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/nuvolsdk/
`

**Comment by jiri-janousek** [comment]
Hello @tailvarlog. I'll upload nuvolasdk to pypi with the next Nuvola release.

**Comment by jiri-janousek** [comment]
Uploaded: https://pypi.org/project/nuvolasdk/4.17.0/
