### ISSUE TITLE
Converting of yandex-music script issues

### ISSUE THREAD

**Issue by d-r-q** [tiliado/nuvolasdk#9]
I my trying to convert yandex-music script with `nuvolasdk convert-project` and get this output:
```
> nuvolasdk convert-project                           
Creating new configure script
Removing obsolete scripts
Trying to update git repo
fatal: pathspec 'Makefile' did not match any files
fatal: pathspec 'metadata.json' did not match any files
fatal: pathspec 'svg-convert.sh' did not match any files
fatal: pathspec 'svg-optimize.sh' did not match any files
Finished!

Tasks to do:

  - Update README.md according to Update.README.md and then remove this template.

```
Instruction in tiliado/nuvola-app-yandex-music#14 says, that nuvolasdk convert-project will:
* "provide you with the new template (template--README.md)"
* update metadata.in.json and integrate.js

, but actually only `Update.README.md` file is created and `.gitignore` file updated.

**Comment by jiri-janousek** [comment]
Hello @d-r-q. Do you have the latest [Nuvola ADK](https://github.com/tiliado/nuvolaruntime/wiki/Nuvola-App-Developer-Kit)? If unsure, run `flatpak update --system; flatpak update --user`.

**Comment by d-r-q** [comment]
It looks like I had an outdated Nuvola ADK:
```
flatpak update --system; flatpak update --user
Looking for updates...
Updating: eu.tiliado.Nuvola/x86_64/stable from nuvola
[####################] 10 metadata, 85 content objects fetched; 63585 KiB transferred in 26 seconds
Now at 8b7fc14c2588.
Updating: eu.tiliado.NuvolaAdk/x86_64/stable from nuvola
[####################] 10 metadata, 12 content objects fetched; 790 KiB transferred in 2 seconds
Now at 25776d1408d4.
Updating: eu.tiliado.NuvolaAppYandexMusic/x86_64/stable from nuvola
[####################] 6 metadata, 2 content objects fetched; 11 KiB transferred in 1 seconds
Now at 3f778c738c1a.
Looking for updates...
```
But `nuvolasdk convert-project` still gives the same results

**Comment by jiri-janousek** [comment]
That's strange. Are you sure you are running `nuvolasdk` from within the ADK and not from a system package? What do these commands show? 

```
flatpak run -d --command=grep eu.tiliado.NuvolaAdk//stable -n 'Running Standard JS style check with autofix' /app/lib/python3.6/site-packages/nuvolasdk/convertproject.py
flatpak run -d --command=grep eu.tiliado.NuvolaAdk//stable -n 'F_TEMPLATE_README_MD_DIFF' /app/lib/python3.6/site-packages/nuvolasdk/convertproject.py
```

**Comment by jiri-janousek** [comment]
This should now work in the latest stable ADK (now uploaded): 

```
$ flatpak run -d --command=nuvolasdk eu.tiliado.NuvolaAdk//stable --version
4.11.17 (17-g3e968ac)
```

**Comment by d-r-q** [comment]
```
> flatpak run -d --command=nuvolasdk eu.tiliado.NuvolaAdk//stable --version
4.11.17 (17-g3e968ac)

> flatpak run -d --command=grep eu.tiliado.NuvolaAdk//stable -n 'Running Standard JS style check with autofix' /app/lib/python3.6/site-packages/nuvolasdk/convertproject.py
error: Failed to export bpf

> flatpak run -d --command=grep eu.tiliado.NuvolaAdk//stable -n 'F_TEMPLATE_README_MD_DIFF' /app/lib/python3.6/site-packages/nuvolasdk/convertproject.py
error: Failed to export bpf

```

**Comment by jiri-janousek** [comment]
Now we can be sure that you have the latest Nuvola ADK with the latest SDK, but that `error: Failed to export bpf` is strange ([it comes from flatpak](https://github.com/flatpak/flatpak/blob/905e38115cdc85f8a869ef33ba22e1a7f208c0d2/common/flatpak-run.c#L2089)). Does it show also if you launch Nuvola ADK as [described in the docs](https://github.com/tiliado/nuvolaruntime/wiki/Nuvola-App-Developer-Kit#set-bash-aliases-and-launch-the-adk)? If you launch `nuvolasdk --version` from the Nuvola ADK environment, does it also show `4.11.17 (17-g3e968ac)`?

**Comment by d-r-q** [comment]
I have this bash aliases:
```
~> cat ~/.zshrc | grep nuvola     
alias nuvolaadk="flatpak run -d --persist= --filesystem=~/0my/Alive/nuvola-apps eu.tiliado.NuvolaAdk"
alias nuvolaadk-sh="flatpak run --command=bash -d --persist= --filesystem=~/0my/Alive/nuvola-apps eu.tiliado.NuvolaAdk"
```

And when I launch `nuvolasdk --version` from Nuvola ADK environment it does also show `4.11.17 (17-g3e968ac)`:
![image](https://user-images.githubusercontent.com/1336130/41396462-38571d28-6fdb-11e8-97e4-3fa5a71a60fe.png)

**Comment by jiri-janousek** [comment]
Great. And does `nuvolasdk convert-project` now work as advertised?

**Comment by d-r-q** [comment]
Yes, looks like, I will check results of conversion later this week

**Comment by d-r-q** [comment]
Works now
